nelmio_api_doc:
    documentation:
        info:
            title: Rover4Me
            description: Aplikacja do wypożycznia rowerów!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
